lib/timesup_web/router.ex
defmodule TimesupWeb.Router do
  use TimesupWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {TimesupWeb.LayoutView, :root}
  end

  pipeline :admin do
    plug :auth
  end

  scope "/", TimesupWeb do
    pipe_through :browser

    get "/", PageController, :index
    post "/create-game", PageController, :create_game
    get "/game/:id/join", PageController, :choose_username
    post "/game/:id/join", PageController, :join_game
    get "/odd_number_of_players", PageController, :odd_number_of_players

    live "/game/:id", GameLive
  end

  scope "/", TimesupWeb do
    pipe_through [:browser, :admin]
    live_dashboard "/dashboard", metrics: TimesupWeb.Telemetry
  end

  # https://hexdocs.pm/plug/1.10.0/Plug.BasicAuth.html#module-low-level-usage
  defp auth(conn, _opts) do
    with {user, password} <- Plug.BasicAuth.parse_basic_auth(conn),
         true <- check_credentials(user, password) do
      conn
    else
      _ -> conn |> Plug.BasicAuth.request_basic_auth() |> halt()
    end
  end

  defp check_credentials(user, password) do
    Plug.Crypto.secure_compare(user, System.get_env("ADMIN_USER")) &&
      Plug.Crypto.secure_compare(password, System.get_env("ADMIN_PASSWORD"))
  end
end

lib/timesup_web/templates/page/404.html.leex
<div class="centered">
  <div class="error-page">
    <div class="error-page-header">
      <h1>404</h1>
      <p>Impossible de retrouver cette partie. Vous pouvez en créer une nouvelle ⬇</p>
    </div>
    <%= form_for :new_game, Routes.page_path(TimesupWeb.Endpoint, :create_game), [class: "new-game-form"], fn _f -> %>
      <%= submit "Nouvelle partie"%>
    <% end %>
  </div>
</div>

lib/timesup_web/templates/page/choose_teams.html.leex
<section class="choose-teams">
  <h1>Répartition des équipes</h1>
  <div>
    <%= render(
      TimesupWeb.PageView,
      "player_list.html",
      Map.put(assigns, :players, Timesup.Game.players_with_no_team(@game))
    ) %>
  </div>
  <%= for {_, team_index} <- Enum.with_index(@game.teams) do %>
    <div class="team">
      <div class="team-header">
        <h2>Équipe <%= team_index + 1 %></h2>
        <button phx-click="choose_team" phx-value-team="<%= team_index %>" class="secondary">
          Rejoindre
        </button>
      </div>
      <%= if Timesup.Game.team(@game, team_index) != [] do %>
        <div>
          <%= render(
            TimesupWeb.PageView,
            "player_list.html",
            Map.put(assigns, :players, Timesup.Game.team(@game, team_index))
          ) %>
        </div>
      <% end %>
    </div>
  <% end %>

  <%= if Timesup.Game.players_with_no_team(@game) == [] do %>
    <div class="start-game-form">
      <button phx-click="start_game">C'est parti !</button>
    </div>
  <% end %>
</section>

lib/timesup_web/templates/page/deck_building.html.leex
<section class="deck-building">
  <aside>
    <h2>Joueurs connectés</h2>
    <div>
      <ul class="player-list">
        <%= for player <- Timesup.Game.get_players(@game) do %>
          <li class="player">
            <%= player.name %>
            <%= if player.ready do %> (prêt·e)<% end %>
            <%= if player.name == @current_user do %> <small>(vous)</small><% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </aside>
  <section class="content">
    <div> <!-- used for horizontal centering -->
      <h1>Mise en place</h1>
      <div>Pour inviter des personnes à rejoindre la partie, envoyez-leur ce lien :
        <div class="share-box">
          <input id="share-url" editable="false" value="<%= Routes.page_url(TimesupWeb.Endpoint, :choose_username, @game.id) %>"/>
          <span>
            <button class="copy-share-url" data-clipboard-target="#share-url">
              Copier
            </button>
          </span>
        </div>
      </div>

      <h2>Les cartes</h2>
      <div class="stack" style="--space: var(--s-1)">
        <p>
          Vous devez constituer une pile de cartes de noms de personnalités (plus ou moins) connues. Vous
          décidez entre vous du nombre de cartes à écrire.
        </p>
        <div class="tip">
          <p>
            il est préférable que tout le monde écrive le même nombre de cartes, sauf
            pour <a href="/odd_number_of_players">un nombre impair de joueur·euses</a>.
          </p>
        </div>
      </div>
      <div>
        <div>Nombre total de cartes : <b><%= Timesup.Game.number_of_cards(@game) %></b></div>
      </div>
      <%= if !Timesup.Game.player_ready?(@game, @current_user) do %>
        <%= f = form_for @card_changeset,
          "#",
          [phx_submit: :add_card, phx_change: :validate_card, class: "add-card-form", as: :card]
        %>
          <div class="input-group">
            <%= label f, :name, "Nouvelle carte" %>
            <%= text_input f, :name, placeholder: "exemple: Beyoncé, Dijkstra...", size: "23" %>
            <%= error_tag f, :name %>
          </div>
          <%= submit "Ajouter", class: "secondary" %>
        </form>
      <% end %>
      <%= if Timesup.Game.get_player_cards(@game, @current_user) !== [] do %>
        <ul class="card-list">
          <%= for {card, i} <- Timesup.Game.get_player_cards(@game, @current_user) |> Enum.with_index() do %>
            <li>
              <div class="card"><%= card %></div>
              <div class="delete">
                <button phx-click="delete_card" phx-value-index="<%= i %>">
                  Supprimer
                </button>
              </div>
            </li>
          <% end %>
        </ul>
      <% end %>
      <%= if Timesup.Game.all_players_ready?(@game) do %>
        <%= if Timesup.Game.number_of_cards(@game) > 0 do %>
          <div class="ready">
            <div><b>Tout le monde est prêt</b></div>
            <button phx-click="start_choosing_teams">Choisir les équipes</button>
          </div>
        <% else %>
          <div class="ready">
            <div><b>Le jeu doit contenir au moins une carte</b></div>
            <button phx-click="toggle_player_ready">Ajouter des cartes</button>
          </div>
        <% end %>
      <% else %>
        <%= if Timesup.Game.player_ready?(@game, @current_user) do %>
          <div class="ready">
            <div><b>En attente des autres joueurs</b></div>
            <div><button phx-click="toggle_player_ready">Ajouter des cartes</button></div>
          </div>
        <% else %>
          <div><button phx-click="toggle_player_ready">Je suis prêt·e</button></div>
        <% end %>
      <% end %>
    </div>
  </section>
</section>

lib/timesup_web/templates/page/first_round.html.leex
<div>C'est à <%= Timesup.GameState.current_player(@game).name %> de faire deviner</div>
<ul>
  <li>
    <div>Équipe 1</div>
      <div><%= Timesup.GameState.team_1_points(@game) %> points</div>
      <ul>
        <%= for player <- Timesup.GameState.team_1(@game) do %>
          <li>
            <%= player.name %>
            <%= if player.name == @current_user do %> (vous)<% end %>
          </li>
        <% end %>
      </ul>
  </li>
  <li>
    <div>Équipe 2</div>
      <div><%= Timesup.GameState.team_2_points(@game) %> points</div>
      <ul>
        <%= for player <- Timesup.GameState.team_2(@game) do %>
          <li>
            <%= player.name %>
            <%= if player.name == @current_user do %> (vous)<% end %>
          </li>
        <% end %>
      </ul>
  </li>
</ul>

<%= if @game.playing do %>
  <div><%= @game.time_remaining %></div>
<% end %>

<%= if Timesup.GameState.current_player(@game).name == @current_user do %>
  <%= if @game.playing do %>
    <div><%= Timesup.GameState.current_card(@game) %></div>
    <%= f = form_for :card_guessed, "#", [phx_submit: :card_guessed] %>
      <%= submit "Deviné !" %>
    </form>
  <% else %>
    <%= f = form_for :start_turn, "#", [phx_submit: :start_turn] %>
      <%= submit "C'est parti !" %>
    </form>
  <% end %>
<% end %>

lib/timesup_web/templates/page/game.html.leex
<%= @game.status %>
<h1>Joueurs</h1>
<ul>
  <%= for player <- Timesup.GameState.get_players(@game) do %>
    <li>
      <%= player.name %>
      <%= if player.ready do %> (prêt.e)<% end %>
      <%= if player.name == @current_user do %> (vous)<% end %>
    </li>
  <% end %>
</ul>

<%= if length(Timesup.GameState.get_player_cards(@game, @current_user)) < 2 do %>
  <%= f = form_for :card, "#", [phx_submit: :add_card] %>
    <%= label f, :name, "Nouvelle carte" %>
    <%= text_input f, :name %>
    <%= submit "Ajouter" %>
  </form>
  <% else %>
    <%= if Timesup.GameState.all_players_ready?(@game) do %>
      <div>Tout le monde est prêt</div>
      <%= f = form_for :choose_teams, "#", [phx_submit: :start_choosing_teams] %>
        <%= submit "Faire les équipes" %>
      </form>
    <% else %>
      <%= if Timesup.GameState.player_ready?(@game, @current_user) do %>
        <div>En attente des autres joueurs</div>
      <% else %>
        <%= f = form_for :ready, "#", [phx_submit: :set_player_ready] %>
          <%= submit "Je suis prêt.e" %>
        </form>
      <% end %>
    <% end %>
<% end %>

<h2>Vos cartes</h2>
<%= for card <- Timesup.GameState.get_player_cards(@game, @current_user) do %>
  <div><%= card %></div>
<% end %>

lib/timesup_web/templates/page/game_ended.html.leex
<section class="game-over">
  <div class="summary">
  <%= for {team, index} <- Enum.with_index(game_summary(@game)) do %>
    <div class="team-summary">
      <%= if index == 0 do %>
        <h1>Bravo à l'<span class="team">équipe&nbsp<%= team.number %></span>&nbsp!</h1>
      <% else %>
        <h2>Et l'<span class="team">équipe&nbsp<%= team.number %></span> <span class="text-sm">(bravo aussi quand même)</span></h2>
      <% end %>
      <div>
        <%= render(
          TimesupWeb.PageView,
          "player_list.html",
          Map.put(assigns, :players, team.players)
        ) %>
      </div>
      <div class="points">
        <div><%= team.points[:round_1] %> + <%= team.points[:round_2] %> + <%= team.points[:round_3] %> =</div>
        <div class="total"><%= team.total %></div>
        <div>points</div>
      </div>
    </div>
  <% end %>
  </div>
  <p>
    Si vous avez trouvé un bug ou que vous avez des idées
    d'améliorations, vous pouvez me contacter <a href="mailto:hello@kimlaitrinh.me">par email</a>
    ou sur <a href="https://twitter.com/KimLaiTrinh">Twitter</a>. Le code est disponible sur
    <a href="https://github.com/kimlai/timesup">Github</a>.
  <p>
  <a class="btn" href="<%= Routes.page_path(TimesupWeb.Endpoint, :index) %>">
    Retour à l'accueil
  </a>
</section>

lib/timesup_web/templates/page/game_started.html.leex
<section class="game-started">
  <aside>
    <%= for {_, team_index} <- Enum.with_index(@game.teams) do %>
      <b>Équipe <%= team_index + 1 %></b>
      <div>
        <%= render(
          TimesupWeb.PageView,
          "player_list.html",
          Map.put(assigns, :players, Timesup.Game.team(@game, team_index))
        ) %>
      </div>
      <ul>
        <%= for {round, i} <- Enum.with_index([:round_1, :round_2, :round_3]) do %>
          <li>Manche <%= i + 1 %>: <%= Timesup.Game.team_points(@game, team_index)[round] %> points</li>
        <% end %>
      </ul>
    <% end %>
  </aside>
  <section class="content">
    <div> <!-- used for horizontal centering -->
      <div class="round-header">
        <%= case @game.round do %>
          <% :round_1 -> %>
            <h1>Manche 1</h1>
            <p>Nombre de mots illimités, pas le droit de passer.</p>
          <% :round_2 -> %>
            <h1>Manche 2</h1><p>Un seul mot, vous avez le droit de passer autant de carte que vous voulez</p>
          <% :round_3 -> %>
            <h1>Manche 3</h1><p>Aucun mot, on mime. Vous avez le droit de passer autant de carte que vous voulez</p>
        <% end %>
      </div>

      <%= if !Timesup.Game.game_over?(@game) do %>
        <%= if @game.playing || Enum.member?(@connect_users, Timesup.Game.current_player(@game)) do %>
          <p>
            C'est à <b><%= Timesup.Game.current_player(@game) %></b> de faire deviner les
            <%= length(@game.deck) %> cartes restantes.
          </p>
        <% else %>
          <p>
            C'est au tour de <b><%= Timesup.Game.current_player(@game) %></b>, mais il semblerait
            qu'il·elle ait quitté la partie (ou perdu sa connexion). Vous pouvez attendre qu'il·elle
            se reconnecte, ou bien passer son tour.
          </p>
          <button phx-click="skip_player" phx-value-player="<%= Timesup.Game.current_player(@game) %>">
            Passer son tour
          </button>
        <% end %>
        <%= if @game.playing do %>
          <span id="time-remaining" phx-hook="RemainingTime" class="time-remaining">
            <%= @game.time_remaining %>
          </span>
          <%= if Timesup.Game.current_player(@game) != @current_user do %>
            <span
              class="current-card <%= if @game.last_card_guessed == nil do %>invisible<% end %>"
            >
              <%= @game.last_card_guessed %>
              <!-- gross hack so that the layout does not change when the card appears -->
              <%= if @game.last_card_guessed == nil do %>placeholder<% end %>
            </span>
          <% else %>
            <span class="current-card"><%= Timesup.Game.current_card(@game) %></span>
            <div class="actions">
              <%= if @game.round != :round_1 do %>
                <button
                 class="secondary"
                 phx-click="pass_card"
                 phx-value-card="<%= Timesup.Game.current_card(@game) %>"
                >
                  Je passe
                </button>
              <% end %>
              <button phx-click="card_guessed" phx-value-deck_length="<%= length(@game.deck) %>">
                Deviné !
              </button>
            </div>
          <% end %>
        <% else %>
          <%= if Timesup.Game.current_player(@game) == @current_user do %>
            <button phx-click="start_turn">C'est parti !</button>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </section>
</section>

lib/timesup_web/templates/page/index.html.eex
<div class="centered">
  <div class="home">
    <div class="home-header">
      <h1>
        Time's Up <span class="online">online</span>
      </h1>
      <p>Pour pouvoir y jouer même quand on est confiné.</p>
    </div>
    <div class="links">
      <%= form_for @conn, Routes.page_path(@conn, :create_game), [class: "new-game-form"], fn _f -> %>
        <%= submit "Nouvelle partie"%>
      <% end %>
      <div class="how-does-it-work">
        <a href="#how-does-it-work">Comment ça marche ?</a>
      </div>
    </div>
  </div>
  <div class="personal-website-link">un site de <a href="http://kimlaitrinh.me">Kim Laï</a></div>
</div>
<section id="how-does-it-work">
  <h2>Comment ça marche ?</h2>
  <p>
    <b>Time's Up online</b> vous permet de jouer au Time's Up tout en respectant les règles de distanciation sociale. Lancer une partie est très simple :
    <ol>
      <li>Pour commencer, lancez une réunion en ligne sur votre service de visioconférence favori et invitez-y les gens avec qui vous souhaitez jouer.</li>
      <li>Une fois en ligne avec vos amis, vous pouvez lancer une nouvelle partie grâce au bouton <b>Nouvelle partie</b> ⬇.</li>
      <li>Envoyez le lien de partage qui vous sera fourni à vos amis afin qu'ils puissent rejoindre la partie.</li>
      <li>Ensuite c'est comme d'habitude, chaque joueur écrit des noms sur des cartes (virtuelles), on fait des équipes, et on joue !</li>
    </ol>
  </p>
  <%= form_for @conn, Routes.page_path(@conn, :create_game), [class: "new-game-form"], fn _f -> %>
    <%= submit "Nouvelle partie"%>
  <% end %>
  </p>
</section>

lib/timesup_web/templates/page/intro_round_1.html.leex
<section class="round-intro">
  <h1>Première manche</h1>
  <p>
    À chaque tour, quelqu'un devra faire deviner aux membres de son équipe les noms
    écrits sur les cartes. Les membres de l'équipe peuvent donner autant de réponses qu'ils le souhaitent,
    mais certaines règles s'appliquent :
  </p>
  <ul>
    <li>
      Il est <b>interdit</b> d'utiliser des <b>traductions</b> (par exemple <em>Michael White</em> pour faire deviner
      <em>Michel Blanc</em>).
    </li>
    <li>
      Il est <b>interdit</b> d'utiliser des mots de la <b>même famille</b> que le nom à faire deviner (par exemple
      <em>Pingouin</em> pour faire deviner <em>Pingu)</em>.
    </li>
    <li>
      Il est <b>interdit</b> d'énumérer des lettres de <b>l’alphabet</b> (par exemple <em>"Ça commence par un B"</em>).
    </li>
  </ul>
  <div class="cta">
    <button phx-click="start_round">Démarrer</button>
  </div>
</section>

lib/timesup_web/templates/page/intro_round_2.html.leex
<section class="round-intro">
  <h1>Deuxième manche</h1>
  <p>
    Cette fois-ci, vous n'avez le droit qu'à <b>un seul mot</b> pour faire deviner les cartes.
    De plus les règles suivantes s'appliquent :
  </p>
  <ul>
    <li>
      Seule la <b>première réponse</b> donnée par les autres membres de l'équipe compte. Si elle
      est fausse, les réponses suivantes ne comptent pas et on passe à la carte suivante.
    </li>
    <li>
      Vous pouvez <b>passer</b> autant de cartes que vous le souhaitez.
    </li>
    <li>
      Les <b>interdictions</b> de la première manche s'appliquent toujours.
    </li>
  </ul>
  <div class="cta">
    <button phx-click="start_round">Démarrer</button>
  </div>
</section>

lib/timesup_web/templates/page/intro_round_3.html.leex
<section class="round-intro">
  <h1>Troisième manche</h1>
  <p>
    Cette fois-ci, vous n'avez plus le droit de parler : Il faut <b>mimer</b> pour faire deviner les cartes.
    De plus les règles suivantes s'appliquent :
  </p>
  <ul>
    <li>
      Il est <b>interdit</b> de fredonner des airs de chanson.
    </li>
    <li>
      Les <b>bruitages</b> et les onomatopées sont <b>autorisés</b> (par exemple <em>"Miaou"</em>).
      Néanmoins vous pouvez décider de les interdire pour augmenter la difficulté.
    </li>
  </ul>
  <div class="cta">
    <button phx-click="start_round">Démarrer</button>
  </div>
</section>

lib/timesup_web/templates/page/join_game.html.eex
<div class="centered">
  <%= form_for @changeset, Routes.page_path(@conn, :join_game, @id), [as: :player, class: "join-game-form"], fn f -> %>
    <div class="input-group">
      <%= label f, :name, "Votre nom" %>
      <%= text_input f, :name, value: Plug.Conn.get_session(@conn, :current_user), required: true %>
      <%= error_tag f, :name %>
    </div>
    <%= submit "Valider" %>
  <% end %>
</div>

lib/timesup_web/templates/page/odd_number_of_players.html.eex
<div id="odd-number-of-players" class="stack" style="--space: var(--s3);">
  <h1>Jouer quand on est un nombre impair</h1>
  <div>
    <div class="stack" style="--space: var(--s1)">
      <p>
        Lorsque vous êtes un nombre impair, il y a deux solutions simples pour équilibrer
        le nombre de cartes écrites par chaque équipe :
      <p>
      <div>
        <ul class="stack">
          <li>
            Quelqu'un n'écrit <b>aucune carte</b>, et rejoint l'équipe la <b>plus nombreuse</b>.
          </li>
          <li>
            Quelqu'un écrit <b>deux fois plus de cartes</b> que les autres, et rejoint l'équipe
            la <b>moins nombreuse</b>.
          </li>
        </ul>
      </div>
      <p>
        Libre à vous de choisir une solution plus compliquée bien sûr.
      </p>
    </div>
  </div>
</div>

lib/timesup_web/templates/page/player_list.html.leex
<ul class="player-list">
  <%= for player <- @players do %>
    <li class="player">
      <%= player.name %>
      <%= if player.name == @current_user do %> <small>(vous)</small><% end %>
      <%= if !Enum.member?(@connect_users, player.name) do %><small>(déconnecté·e)</small><% end %>
    </li>
  <% end %>
</ul>